-- Cache table
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = '{TABLE_NAME}'
)
BEGIN
CREATE TABLE {TABLE_NAME} (
    [key] NVARCHAR(255) NOT NULL PRIMARY KEY,
    [value] NVARCHAR(MAX) NOT NULL,
    [soft_ttl] INT NOT NULL,
    [hard_ttl] INT NOT NULL
    );
CREATE INDEX idx_soft_ttl ON {TABLE_NAME} ([soft_ttl]);
CREATE INDEX idx_hard_ttl ON {TABLE_NAME} ([hard_ttl]);
END;

-- Locks table
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = '{LOCKS_TABLE_NAME}'
)
BEGIN
CREATE TABLE {LOCKS_TABLE_NAME} (
    [key] NVARCHAR(255) NOT NULL PRIMARY KEY,
    [token] NVARCHAR(255) NOT NULL,
    [expiry] INT NOT NULL
    );
CREATE INDEX idx_expiry ON {LOCKS_TABLE_NAME} ([expiry]);
END;