<?php
/**
 * Events Cache (Auto-Generated)
 * 
 * This file contains event listener registrations only.
 * It is auto-generated when routes are reloaded. DO NOT EDIT THIS FILE.
 * 
 * To override events, create/edit system/config/events.php
 * 
 * Generated: 2026-01-26 15:39:14
 */
return [
];
