<?php
/**
 * Routes Cache (Auto-Generated)
 * 
 * This file contains route definitions only.
 * It is auto-generated when routes are reloaded. DO NOT EDIT THIS FILE.
 * 
 * To override routes, create/edit system/config/routes.php
 * 
 * Generated: 2026-01-26 15:39:14
 */
return [
	'admin-index' => [
		'path' => '/admin',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => false,
		'controller' => 'Modules\Admin\Controllers\FrontController::dashboard',
		'middleware' => [
			'System\Security\Middleware\RequiredPermissionMiddleware' => ['admin_access'],
		],
	],
	'home-page' => [
		'path' => '/',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => false,
		'controller' => 'Modules\Dashboard\Controllers\FrontController::getIndex',
		'middleware' => [
		],
	],
	'dev-test' => [
		'path' => '/test',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => false,
		'controller' => 'Modules\Devtest\Controllers\Devtest::getIndex',
		'middleware' => [
		],
	],
	'installer' => [
		'path' => '/install',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => false,
		'controller' => 'Modules\Install\Controllers\FrontController::getIndex',
		'middleware' => [
		],
	],
	'installer-ajax' => [
		'path' => '/install',
		'methods' => ['POST'],
		'isAjax' => true,
		'isInternal' => false,
		'controller' => 'Modules\Install\Controllers\AjaxController::postIndex',
		'middleware' => [
		],
	],
	'installer-ajax-tables' => [
		'path' => '/install/tables',
		'methods' => ['POST'],
		'isAjax' => true,
		'isInternal' => false,
		'controller' => 'Modules\Install\Controllers\AjaxController::postTables',
		'middleware' => [
		],
	],
	'installer-ajax-finalize' => [
		'path' => '/install/finalize',
		'methods' => ['POST'],
		'isAjax' => true,
		'isInternal' => false,
		'controller' => 'Modules\Install\Controllers\AjaxController::postFinalize',
		'middleware' => [
		],
	],
	'site-nav.widget' => [
		'path' => '/navigation/site',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => true,
		'controller' => 'Modules\Navigation\Controllers\WidgetController::buildSiteNav',
		'middleware' => [
		],
	],
	'top-players-score' => [
		'path' => '/player/list/top/{limit<\d+>}/score',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => true,
		'controller' => 'Modules\Player\Controllers\WidgetController::getTopPlayersByScore',
		'middleware' => [
		],
	],
	'featured-servers' => [
		'path' => '/server/list/featured/{limit<\d+>}',
		'methods' => ['GET'],
		'isAjax' => false,
		'isInternal' => true,
		'controller' => 'Modules\Server\Controllers\WidgetController::featuredServers',
		'middleware' => [
		],
	]
];
