<?php
/**
 * Plexis CMS, the Battlefield 2 private statistics frontend.
 *
 * Originally created for use by the community of BF2Statistics.com
 * before it shut down in April 2023.
 *
 * PHP Version 8.4.2 or newer required.
 *
 * @author:       Steven Wilson
 * @copyright:    Copyright 2025, Steven Wilson, All rights reserved.
 * @license:      GNU GPL v3
 */

namespace Application\Middleware;

use Application\Security\Authentication;
use Application\Security\UserIdentity;
use Exception;
use System\Database\DbFactory;
use System\Diagnostics\LogWriter;
use System\Http\MiddlewareInterface;
use System\Http\Request;
use System\Http\Response;

/**
 * Middleware to handle user authentication. This middleware MUST BE loaded AFTER the Session
 * has been loaded and attached to the `Request`
 *
 * This middleware processes authentication cookies in incoming requests, validates
 * user sessions, and attaches authenticated user information to the request session.
 * It ensures session integrity using encryption, decryption, and token validation.
 * If authentication is invalid, the middleware enforces user logout.
 */
class AuthenticationMiddleware implements MiddlewareInterface
{
    protected bool $setNewResponseCSRF = false;

    /**
     * Processes an incoming request and applies authentication.
     *
     * This is part of the middleware pipeline. The method checks for a valid
     * authentication cookie, validates the user session, and attaches the user
     * identity to the session. If no valid session is found, the request proceeds
     * without an authenticated user.
     *
     * @param Request $request The incoming HTTP request.
     * @param callable $next   The next middleware or request handler (a callable).
     *
     * @return Response The response generated by the next middleware or handler.
     *
     * @throws Exception If an error occurs during session validation or processing.
     */
    public function process(Request $request, callable $next): Response
    {
        // Load session cookie
        $user = $this->processAuthCookie($request);
        if ($user instanceof UserIdentity)
        {
            $request->session()->attachUser($user);
        }
        else
        {
            $guest = new UserIdentity(0, []);
            $request->session()->attachUser($guest);
        }

        // Continue down the pipe
        $response = $next($request);

        // During an ajax request, we need to set the CSRF token in the response using a custom header
        if ($this->setNewResponseCSRF)
        {
            $response->header('X-CSRF-Token', $request->session()->get('csrf_token'));
        }

        return $response;
    }

    /**
     * Loads the session cookie from the request and initializes a user identity.
     *
     * This method decrypts the session cookie, validates it, and fetches user session
     * information from the database. If the session is valid, it returns a `UserIdentity`
     * instance. Otherwise, it forces the user to logout and returns `null`.
     *
     * @param Request $request The incoming request containing the session cookie.
     *
     * @return UserIdentity|null The authenticated user's identity, or `null` if no valid session was found.
     *
     * @throws Exception If any error occurs during cookie decryption or session validation.
     */
    protected function processAuthCookie(Request $request): ?UserIdentity
    {
        // Use the database and session cookie to init a user identity
        $logWriter = LogWriter::Instance('debug');
        $cookie = $request->cookie('auth');
        if (empty($cookie))
        {
            $logWriter->logDebug("[Auth] No Auth cookie found.");
            return null;
        }
        else if (substr_count($cookie, '::') != 1)
        {
            $logWriter->logWarning("[Auth] Invalid session cookie. Forcing logout");
            Authentication::Logout();
            return null;
        }

        // Grab selector and token
        list($selector, $cookieToken) = explode('::', $cookie);
        $connection = DbFactory::GetConnection('web');
        $query = $connection->from('bf2web_sessions')->where('selector')->equals($selector)->apply();
        $statement = $query->execute();

        // Fetch session row
        if (!$statement->hasRows)
        {
            $logWriter->logWarning("[Auth] Invalid selector in session cookie. Forcing logout");
            Authentication::Logout();
            return null;
        }

        // 1% chance to clean up old sessions, so one lucky winner get this now and then
        if (mt_rand(1, 100) === 1)
        {
            $logWriter->logDebug("[Auth] Clearing expired sessions.");
            $connection->delete('bf2web_sessions')->where('expires')->lessThan(time())->execute();
        }

        // Log
        $logWriter->logDebug("[Auth] Valid session cookie format exists, validating session.");
        $sessionRow = $statement->fetch();
        $statement->closeCursor();

        // Get user id
        $userid = (int) $sessionRow['account_id'];

        // Get client IP address
        $clientIp = Request::ClientIp();
        if ($sessionRow['expires'] < time())
        {
            // Session time is expired
            $logWriter->logDebug('[Auth] User session expired, Forced logout');
            Authentication::Logout();
        }
        else if (!$this->validateAuthToken($cookieToken, $sessionRow['validator']))
        {
            // Session is invalid
            $logWriter->logSecurity("[Auth] Session cookie failed validation for user ({$userid}). Forcing logout on all devices");
            Authentication::Logout(true, true, $userid);
        }
        else
        {
            // Get the user
            $query = $connection->from('bf2web_accounts')->where('id')->equals($userid)->apply();
            $statement = $query->execute();
            if (!$statement->hasRows)
            {
                $logWriter->logWarning("[Auth] Invalid user id attached to session cookie. Forcing logout");
                Authentication::Logout(true);
                return null;
            }

            // Fetch data row
            $userRow = $statement->fetch();
            $statement->closeCursor();

            // Check to see if the session refresh has expired
            if ($sessionRow['refresh'] < time())
            {
                // Rotate the auth token to prevent hijacking
                Authentication::RotateValidator($selector, (int)$sessionRow['expires'], $clientIp);

                // Grab session
                $session = $request->session();
                $oldToken = $session->get('csrf_token');

                // Rotate the CSRF token
                $session->rotateCsrfToken();

                // Update the CSRF token in the post data if just expired
                if ($request->post('csrf_token') !== null)
                {
                    if ($oldToken != null && $oldToken == $request->post('csrf_token'))
                    {
                        // Rotate the CSRF token and update the post data
                        $request->post('csrf_token', $session->get('csrf_token'));
                        $this->setNewResponseCSRF = true;
                    }
                }
            }

            // User is good and logged in
            return new UserIdentity($userid, $userRow);
        }

        return null;
    }

    /**
     * Validates a session token against the expected proof token.
     *
     * This method regenerates the proof token using the client-provided `cookieToken`
     * (from the session cookie), the client’s fingerprint, and the server's secret key.
     * The regenerated proof token is compared against the stored proof token to verify
     * if the session is authentic. A constant-time comparison is used to prevent
     * timing-based attacks.
     *
     * @param string $cookieToken The client-provided `cookieToken` (partial token from the cookie).
     * @param string $proofToken  The server-stored proof token for validation (binary format).
     *
     * @return bool Returns `true` if the token is valid and matches the proof token,
     *              or `false` otherwise.
     */
    protected function validateAuthToken(string $cookieToken, #[\SensitiveParameter] string $proofToken): bool
    {
        // Regenerate the proof token
        $fingerprint = Authentication::GetClientFingerprint();
        $data = $cookieToken . '::' . $fingerprint;

        // Generate HMAC using server-side secret
        $key = \System::Config()->get('security_seed');
        $against = hash_hmac('sha256', $data, $key);

        // Use constant-time comparison to prevent timing attacks
        return hash_equals($against, $proofToken);
    }
}